### PR TITLE
added interval support

### PR DESCRIPTION
**Pull request by CruelMoney**
I needed to use a smaller interval than a day, and added the option to use an hourly interval.
Could be made more versatile.

### CODE REVIEW

**Comment by scerelli** [comment]
are you planning to implement also the android part?

**Comment by CruelMoney** [comment]
> thanks @CruelMoney
> are you planning to implement also the android part?

Yes, probably within a month.

**Comment by scerelli** [comment]
ok so let's keep this open until it's finished

**Comment by scerelli** [comment]
seems good to me, @CruelMoney  if you fix the conflicts i think we can merge this.

cc @Francesco-Voto

**Comment by CruelMoney** [comment]
Just finished the android implementation and added details to the readme. How does it look?

**Comment by scerelli** [comment]
@CruelMoney looks good to me i'm gonna merge this

**Pull request merged**
