### PR TITLE
Version bumped to 0.3.1

### PR DESCRIPTION
**Pull request by rlems**
Bump to new version for updating by package managers

### CODE REVIEW

**Comment by rlems** [comment]
I don't know if newly created tags come along in a merge request, if not a new tag should be created

**Comment by rlems** [comment]
@Francesco-Voto Could you take a look at this? Thank you.

**Comment by Francesco-Voto** [comment]
Sorry I am currently working on the Sleep Analysis.
Next release will not be a patch but a minor

**Comment by rlems** [comment]
@Francesco-Voto Any indication on this? I'm currently using a custom fork of this repo, but I'd rather use your official repo,

**Pull request closed without merging**
